### ISSUE TITLE
compose替换镜像后报错

### ISSUE THREAD

**Issue by crhope** [linyuan0213/nas-tools#21]
Traceback (most recent call last):
  File "/nas-tools/run.py", line 29, in <module>
    from web.action import WebAction
  File "/nas-tools/web/action.py", line 22, in <module>
    from app.brushtask import BrushTask
  File "/nas-tools/app/brushtask.py", line 12, in <module>
    from app.downloader import Downloader
  File "/nas-tools/app/downloader/__init__.py", line 1, in <module>
    from .downloader import Downloader
  File "/nas-tools/app/downloader/downloader.py", line 11, in <module>
    from app.conf import ModuleConf
  File "/nas-tools/app/conf/__init__.py", line 1, in <module>
    from .systemconfig import SystemConfig
  File "/nas-tools/app/conf/systemconfig.py", line 3, in <module>
    from app.helper import DictHelper
  File "/nas-tools/app/helper/__init__.py", line 1, in <module>
    from .chrome_helper import ChromeHelper, init_chrome
  File "/nas-tools/app/helper/chrome_helper.py", line 11, in <module>
    from app.utils import SystemUtils, RequestUtils
  File "/nas-tools/app/utils/__init__.py", line 10, in <module>
    from .torrent import Torrent
  File "/nas-tools/app/utils/torrent.py", line 7, in <module>
    import libtorrent
ModuleNotFoundError: No module named 'libtorrent'

**Comment by linyuan0213** [comment]
这个问题已经修复了，遇到的更新一下
